aeropuertos = [
    {"airport_id": "ATL", "airport_name": "Hartsfield–Jackson Atlanta International Airport", "city": "Atlanta", "country": "USA"},
    {"airport_id": "PEK", "airport_name": "Beijing Capital International Airport", "city": "Beijing", "country": "China"},
    {"airport_id": "DXB", "airport_name": "Dubai International Airport", "city": "Dubai", "country": "UAE"},
    {"airport_id": "LAX", "airport_name": "Los Angeles International Airport", "city": "Los Angeles", "country": "USA"},
    {"airport_id": "HND", "airport_name": "Tokyo Haneda Airport", "city": "Tokyo", "country": "Japan"},
    {"airport_id": "ORD", "airport_name": "O'Hare International Airport", "city": "Chicago", "country": "USA"},
    {"airport_id": "LHR", "airport_name": "Heathrow Airport", "city": "London", "country": "United Kingdom"},
    {"airport_id": "HKG", "airport_name": "Hong Kong International Airport", "city": "Hong Kong", "country": "Hong Kong"},
    {"airport_id": "CDG", "airport_name": "Charles de Gaulle Airport", "city": "Paris", "country": "France"},
    {"airport_id": "DFW", "airport_name": "Dallas/Fort Worth International Airport", "city": "Dallas/Fort Worth", "country": "USA"},
    {"airport_id": "AMS", "airport_name": "Amsterdam Airport Schiphol", "city": "Amsterdam", "country": "Netherlands"},
    {"airport_id": "FRA", "airport_name": "Frankfurt Airport", "city": "Frankfurt", "country": "Germany"},
    {"airport_id": "IST", "airport_name": "Istanbul Airport", "city": "Istanbul", "country": "Turkey"},
    {"airport_id": "CAN", "airport_name": "Guangzhou Baiyun International Airport", "city": "Guangzhou", "country": "China"},
    {"airport_id": "JFK", "airport_name": "John F. Kennedy International Airport", "city": "New York", "country": "USA"},
    {"airport_id": "SIN", "airport_name": "Singapore Changi Airport", "city": "Singapore", "country": "Singapore"},
    {"airport_id": "DEN", "airport_name": "Denver International Airport", "city": "Denver", "country": "USA"},
    {"airport_id": "BKK", "airport_name": "Suvarnabhumi Airport", "city": "Bangkok", "country": "Thailand"},
    {"airport_id": "SFO", "airport_name": "San Francisco International Airport", "city": "San Francisco", "country": "USA"},
    {"airport_id": "KUL", "airport_name": "Kuala Lumpur International Airport", "city": "Kuala Lumpur", "country": "Malaysia"},
    {"airport_id": "MAD", "airport_name": "Adolfo Suárez Madrid–Barajas Airport", "city": "Madrid", "country": "Spain"},
    {"airport_id": "MUC", "airport_name": "Munich Airport", "city": "Munich", "country": "Germany"},
    {"airport_id": "MIA", "airport_name": "Miami International Airport", "city": "Miami", "country": "USA"},
    {"airport_id": "ICN", "airport_name": "Incheon International Airport", "city": "Seoul", "country": "South Korea"},
    {"airport_id": "BCN", "airport_name": "Barcelona–El Prat Airport", "city": "Barcelona", "country": "Spain"}
]

conexiones = [
    {"from": "ATL", "to": "LAX", "distance": 3111},
    {"from": "DXB", "to": "LHR", "distance": 5499},
    {"from": "HND", "to": "SIN", "distance": 5322},
    {"from": "ORD", "to": "PEK", "distance": 10854},
    {"from": "HKG", "to": "JFK", "distance": 12964},
    {"from": "CDG", "to": "DXB", "distance": 5246},
    {"from": "DFW", "to": "DEN", "distance": 1062},
    {"from": "AMS", "to": "MIA", "distance": 7463},
    {"from": "FRA", "to": "ICN", "distance": 8729},
    {"from": "IST", "to": "KUL", "distance": 8527},
    {"from": "CAN", "to": "SFO", "distance": 11134},
    {"from": "BKK", "to": "MUC", "distance": 8856},
    {"from": "DEN", "to": "ATL", "distance": 1937},
    {"from": "SFO", "to": "ORD", "distance": 2966},
    {"from": "MAD", "to": "LAX", "distance": 9331},
    {"from": "MUC", "to": "BCN", "distance": 1054},
    {"from": "MIA", "to": "JFK", "distance": 1759},
    {"from": "PEK", "to": "CDG", "distance": 8172},
    {"from": "LAX", "to": "HND", "distance": 8857},
    {"from": "DXB", "to": "JFK", "distance": 11004},
    {"from": "ATL", "to": "DXB", "distance": 12259},
    {"from": "LHR", "to": "SFO", "distance": 8639},
    {"from": "HKG", "to": "LAX", "distance": 11644},
    {"from": "SIN", "to": "DXB", "distance": 5844},
    {"from": "ORD", "to": "LHR", "distance": 6354},
    {"from": "DFW", "to": "PEK", "distance": 11279},
    {"from": "AMS", "to": "DXB", "distance": 5173},
    {"from": "FRA", "to": "ATL", "distance": 7404},
    {"from": "IST", "to": "JFK", "distance": 8008},
    {"from": "CAN", "to": "AMS", "distance": 9157},
    {"from": "MIA", "to": "LHR", "distance": 7126},
    {"from": "BCN", "to": "DXB", "distance": 5128},
    {"from": "MUC", "to": "SIN", "distance": 10133},
    {"from": "ICN", "to": "PEK", "distance": 956},
    {"from": "BKK", "to": "HKG", "distance": 1696},
    {"from": "SFO", "to": "PEK", "distance": 9503},
    {"from": "KUL", "to": "DXB", "distance": 5581},
    {"from": "MAD", "to": "JFK", "distance": 5782},
    {"from": "DEN", "to": "LHR", "distance": 7480},
    {"from": "ATL", "to": "MIA", "distance": 951},
    {"from": "DXB", "to": "IST", "distance": 2984},
    {"from": "LAX", "to": "CDG", "distance": 9098},
    {"from": "HND", "to": "SFO", "distance": 8253},
    {"from": "ORD", "to": "MUC", "distance": 7215},
    {"from": "HKG", "to": "FRA", "distance": 9289},
    {"from": "CDG", "to": "MIA", "distance": 7434},
    {"from": "DFW", "to": "AMS", "distance": 7970},
    {"from": "AMS", "to": "SIN", "distance": 10422},
    {"from": "FRA", "to": "DEN", "distance": 7961},
    {"from": "IST", "to": "CAN", "distance": 7759},
    {"from": "JFK", "to": "ICN", "distance": 11062},
    {"from": "SIN", "to": "BKK", "distance": 1425},
    {"from": "DEN", "to": "PEK", "distance": 10058},
    {"from": "SFO", "to": "DXB", "distance": 13340},
    {"from": "KUL", "to": "JFK", "distance": 15149},
    {"from": "MAD", "to": "IST", "distance": 2824},
    {"from": "MUC", "to": "LAX", "distance": 9514},
    {"from": "MIA", "to": "BCN", "distance": 7670},
    {"from": "ICN", "to": "DXB", "distance": 6878},
    {"from": "BKK", "to": "LHR", "distance": 9551},
    {"from": "MAD", "to": "DXB", "distance": 5658.72},
    {"from": "BCN", "to": "MUC", "distance": 1094.88},
    {"from": "DFW", "to": "MAD", "distance": 7989.93},
    {"from": "HKG", "to": "IST", "distance": 8019.74},
    {"from": "CDG", "to": "MUC", "distance": 682.94},
    {"from": "ATL", "to": "DFW", "distance": 1171.06},
    {"from": "CAN", "to": "SIN", "distance": 2568.33},
    {"from": "MIA", "to": "CAN", "distance": 13907.26},
    {"from": "LAX", "to": "CAN", "distance": 11666.86},
    {"from": "HND", "to": "CAN", "distance": 2982.72},
    {"from": "HKG", "to": "DEN", "distance": 12293.02},
    {"from": "SIN", "to": "KUL", "distance": 296.35},
    {"from": "FRA", "to": "MIA", "distance": 7817.78},
    {"from": "LAX", "to": "FRA", "distance": 9315.01},
    {"from": "KUL", "to": "IST", "distance": 8455.64},
    {"from": "ATL", "to": "MUC", "distance": 7609.92},
    {"from": "HND", "to": "FRA", "distance": 9358.83},
    {"from": "BKK", "to": "BCN", "distance": 10150.81},
    {"from": "ORD", "to": "MAD", "distance": 6762.43},
    {"from": "HND", "to": "MAD", "distance": 10760.75},
    {"from": "MIA", "to": "AMS", "distance": 7411.59},
    {"from": "HND", "to": "LHR", "distance": 9564.94},
    {"from": "IST", "to": "MUC", "distance": 1491.39},
    {"from": "KUL", "to": "ATL", "distance": 15808.63},
    {"from": "IST", "to": "HKG", "distance": 8031.17},
    {"from": "PEK", "to": "HND", "distance": 2094.38},
    {"from": "BCN", "to": "ICN", "distance": 10008.98},
    {"from": "CAN", "to": "MIA", "distance": 13907.26},
    {"from": "LHR", "to": "JFK", "distance": 5555.45},
    {"from": "IST", "to": "DEN", "distance": 10030.69},
    {"from": "ATL", "to": "HKG", "distance": 14227.54},
    {"from": "BKK", "to": "LAX", "distance": 13247.32},
    {"from": "KUL", "to": "PEK", "distance": 4375.02},
    {"from": "ICN", "to": "FRA", "distance": 8563.56},
    {"from": "ICN", "to": "ATL", "distance": 11196.23},
    {"from": "DEN", "to": "HKG", "distance": 12293.02},
    {"from": "IST", "to": "ICN", "distance": 8286.61},
    {"from": "JFK", "to": "ATL", "distance": 1207.18},
    {"from": "MIA", "to": "IST", "distance": 9658.29},
    {"from": "SFO", "to": "CAN", "distance": 11601.45},
    {"from": "HKG", "to": "DFW", "distance": 13023.67},
    {"from": "LHR", "to": "CDG", "distance": 344.0},
    {"from": "HKG", "to": "PEK", "distance": 1958.75},
    {"from": "LHR", "to": "IST", "distance": 2503.25},
    {"from": "SFO", "to": "HND", "distance": 8279.01},
    {"from": "FRA", "to": "BCN", "distance": 1102.54},
    {"from": "MIA", "to": "PEK", "distance": 12960.95},
    {"from": "BKK", "to": "PEK", "distance": 3296.91},
    {"from": "DFW", "to": "IST", "distance": 10072.68},
    {"from": "MUC", "to": "MIA", "distance": 8066.56},
    {"from": "MUC", "to": "PEK", "distance": 7828.27},
    {"from": "DEN", "to": "MAD", "distance": 7978.05},
    {"from": "BKK", "to": "CDG", "distance": 9481.86},
    {"from": "ORD", "to": "BCN", "distance": 7164.08},
    {"from": "HND", "to": "ICN", "distance": 1164.05},
    {"from": "HND", "to": "MUC", "distance": 9363.95},
    {"from": "PEK", "to": "BKK", "distance": 3296.91},
    {"from": "BCN", "to": "LHR", "distance": 1137.99},
    {"from": "BKK", "to": "HND", "distance": 4598.52},
    {"from": "BKK", "to": "DXB", "distance": 4913.96}
]
